name: Daily README Update

on:
  schedule:
    - cron: "30 17 * * *" # Runs 11:00 PM IST
  workflow_dispatch: # Optional: manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run update_readme.py
        run: python update_readme.py

      - name: Commit and Push
        run: |
          git config user.name "Ratneshtripathi07"
          git config user.email "ratneshgeetatripathi@gmail.com"
          git add README.md
          git commit -m "$(date +'%d-%m-%Y') ✅" || echo "No changes to commit"
          git push
